// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_biIUufPNn13Q8vFfhtmHAXq5XSeyTE',
    appId: '1:1058644204081:web:45cf9658ade23610d99310',
    messagingSenderId: '1058644204081',
    projectId: 'ecpods-982ca',
    authDomain: 'ecpods-982ca.firebaseapp.com',
    storageBucket: 'ecpods-982ca.appspot.com',
    measurementId: 'G-KY2RBCTB45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbE-pP-oA-7xbYwPo3eLodOLEKPnpv5QU',
    appId: '1:1058644204081:android:273deaa8a250147bd99310',
    messagingSenderId: '1058644204081',
    projectId: 'ecpods-982ca',
    storageBucket: 'ecpods-982ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuXd7LBpgi7sj-ULvpJZIZnd72mVcwJI',
    appId: '1:1058644204081:ios:b574464a60d1a033d99310',
    messagingSenderId: '1058644204081',
    projectId: 'ecpods-982ca',
    storageBucket: 'ecpods-982ca.appspot.com',
    iosBundleId: 'com.eccono.ecpods',
  );
}
